id: capella_signup_process
learningObjectives:
  - Learn the Couchbase Capella sign-up process.
hints: []
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Now that you're aware of what Capella can do, let's create an account.
          - text: To sign up, visit [Couchbase Capella
              Sign-Up](https://cloud.couchbase.com/signup).
          - text: You'll need to provide some basic details to create your free account
              quickly.
          - text: Having an account is the first step in connecting to Capella's features.
          - text: These features assist in deploying efficient modern applications.
          - text: Once signed up, let me know, and we can proceed.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
