id: create_vector_search_index
learningObjectives:
hints: []
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Let's get serious about indexing. We'll create a [vector search index](https://docs.couchbase.com/server/current/vector-search/vector-search.html).
          - text: Indexing is crucial for executing similarity searches efficiently. Use Couchbase Shell to create the index with `vector create-index`.
          - text: Provide bucket name and specified metrics for dot-product similarity. Indexing prepares data for swift, precise querying. When your index is ready, signal for the next step.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
