id: import_pre_generated_embeddings
learningObjectives:
hints: []
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Time to import data with embeddings. It's like importing your childhood photo album.
          - text: "[Pre-generated embeddings](https://www.couchbase.com/blog/what-are-vector-embeddings/) offer a quick start for your searches. Jump into the `individual_items_with_embedding` directory."
          - text: Edit `./config_file/config` with your Couchbase Capella details. Use Couchbase Shell to bring your data directly into the bucket. Adjustments in the shell ensure you're communicating with your cluster. Signal when you're done importing so we can proceed.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
